export const ADD_MESSAGE = "ADD_MESSAGE"
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
export const ADD_USER = "ADD_USER"
export const USERS_LIST = "USERS_LIST"
export const CONNECT = "CONNECT"
export const DISCONNECT = "DISCONNECT"
export const ADD_NAME = "ADD_NAME"